name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          mkdir -p output
          cp -r ./src ./output/
          zip -r output/code.zip ./output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shell-script-artifact
          path: output/code.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      resource_group_name: "RG-VaibhavUniyal-POC"
      app_service_name: "appdemowebjobtest0001"
      webjob_name: "webjob-1"
      bicep_file_path: "./bicep/main.bicep"
      app_service_plan_id: "/subscriptions/99cb61e0-6f5e-453f-9bf6-bc478df73d4b/resourceGroups/RG-VaibhavUniyal-POC/providers/Microsoft.Web/serverFarms/aspcdvaibhavuniyalpoc0024"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy WebJob to Azure App Service
        run: |
          az deployment group create \
            --resource-group $resource_group_name \
            --template-file $bicep_file_path \
            --parameters appServiceName="$app_service_name" \
                         webJobName="$webjob_name"
