name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          mkdir -p output
          cp -r ./src ./output/
          zip -r output/code.zip ./output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: shell-script-artifact
          path: output/code.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Install jq
        run: |
          sudo apt-get install jq

      - name: Set up Azure credentials from secret
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
          export CLIENT_ID=$(jq -r .["clientId"] azure_credentials.json)
          export SUBSCRIPTION_ID=$(jq -r .["subscriptionId"] azure_credentials.json)
          export TENANT_ID=$(jq -r .["tenantId"] azure_credentials.json)
          export CLIENT_SECRET=$(jq -r .["clientSecret"] azure_credentials.json)

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: shell-script-artifact
          path: ./output

      - name: Deploy WebJob to Azure App Service
        run: |
          resource_group_name="RG-VaibhavUniyal-POC"
          app_service_name="appdemowebjobtest0001"
          webjob_name="webjob-1"
          zip_file_path="./output/code.zip"

          az webapp webjob continuous add \
            --resource-group $resource_group_name \
            --name $app_service_name \
            --webjob-name $webjob_name \
            --file $zip_file_path
