name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          mkdir -p ./App_Data/jobs/continuous/WebJob2
          cp -r ./src/* ./App_Data/jobs/continuous/WebJob2
          zip -r ./webjob.zip ./App_Data

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webjob-artifact
          path: ./webjob.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download WebJob Artifact
        uses: actions/download-artifact@v4
        with:
          name: webjob-artifact

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy WebJob to Azure Web App
        run: |
          WEBAPP_NAME="appdemowebjobstest001"
          RESOURCE_GROUP="RG-VaibhavUniyal-POC"
          ARTIFACT_PATH="./webjob.zip"

          az webapp deploy --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP --src-path $ARTIFACT_PATH --type zip
